config/routes.rb
Rails.application.routes.draw do
  

  get 'site/home'

  get 'site/about'

  get 'site/contact'
  
  

  get 'site/home'

  get 'site/about'

  get 'site/contact'
  
  get '/about' => 'site#about'
  
  get '/contact' => 'site#contact'
  
  get '/admin' => 'user#admin_login'
  
  get '/logout' => 'user#logout'
  
  get '/cart' => 'cart#index'
  
  get '/cart' => 'cart#clearCart'
  
  get '/cart/:id' => 'cart#add' 
  
 get '/home'  => 'site#home'
 

  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
  class CartController < ApplicationController
  def add
    # get the ID of the product
	id = params[:id]
    
	# if the cart has already been created, use the existing cart
	# else create a blank cart
	if session[:cart] then
		cart = session[:cart]
	else
		session[:cart] = {}
		cart = session[:cart]
	end
	
	# if the product has alreadd been added to the cart, increment the value
	# else set the value to 1
    	if cart[id] then
		cart[id] = cart[id] + 1
	else
		cart[id] = 1
	end
	
	# redirect to the cart display page
   	 redirect_to :action => :index
  end #end add method 

  def clearCart
    	# set the session variable to nil and redirect
    	session[:cart] = nil
	redirect_to :action => :index
  end

  def index
	# if there is a cart, pass it to the page for display
	# else pass an empty value
    	if session[:cart] then
		@cart = session[:cart]
	else
		@cart = {}
	end
  end
  
end

  

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :size, :brand)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

    def login
      end
    
      def admin_login
        session[:login] = 1
        session[:cart] = nil
        flash[:notice] = "Admin Login Successful!!"
        redirect_to :controller => :items
      end
    
      def logout
        session[:login] = nil
        session[:cart] = nil
        flash[:notice] = "You have successfully logged out!!"
        redirect_to :controller => :items
      end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>

<% if @cart.empty? %>
    <p>Your Cart is empty.</p>
<% end %>

<% total = 0 %>
	
<table class="cart">
    <tr>
        <td class="legend"></td>
        <td class="legend">Item</td>
        <td class="legend">Price</td>
        <td class="legend">Qty</td>
        <td class="legend">Total</td>
    </tr>
	
<% @cart.each do | id, quantity | %>
    <% item = Item.find_by_id(id) %>
    <tr>
        <td>
            <div class="image">
                <%= link_to (image_tag item.image_url, :style => "height:150px"), item %>
            </div>
        </td>
        <td class="title"><%= link_to item.title, item %></td>
        <td class="price"><%= number_to_currency(item.price) %></td>
        <td class="quantity"><%= quantity %><br /></td>
        <td class="price">
        <%= number_to_currency(quantity * item.price, :unit => "€") %>
    </td>
    </tr>
    <% total += quantity * item.price %>
<% end %>

    <tr>
        <td colspan="4">
            <div class="total">Total:</div>
        </td>
        <td>
            <div class="price"><%= number_to_currency(total, :unit => "€") %></div>
        </td>
    </tr>
</table>

<p>
     <%= link_to 'Continue Shopping', :controller => :items %>
</p>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Product Catalog</h1>
<br>
<table class="catalog">

<% @items.each do |item| %>
  <tr>
    <td>
        <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:200px"), item %>
        </div>
    </td>
    <td>
        <div class="title">
            <%= link_to item.title, item %>
        </div>
        <div class="description">
            <%=h item.description %>
        </div>
        <div class="price">
            <%= number_to_currency(item.price, :unit => "€") %>
        </div>
        <div class="links">
            <% if session[:login] == 1 %>
               <%= link_to 'Edit', edit_item_path(item) %> |
                <%= link_to 'Destroy', item, :confirm => 'Are you sure?', :method => :delete %>
                <% else %>
                    <a href ="/cart/<%= item.id %>" >Add to Cart</a><br><br>
                    <% end %>
        </div>
       
    </td>
  </tr>

<% end %>
</table>
<% if session[:login] == 1 %>
<p><%= link_to 'New item', new_item_path %></p>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Size:</strong>
  <%= @item.size %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leitrim Surf Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
       <div id='header'>
        
        </div>
        <div id='menu'>
        <div id="navbar">
            <ul>
            <li><a href="/home">Home</a></li>
            <li><a href="/items">Products</a></li>
            <li><a href="/cart#index">View Cart</a></li>
             <li><a href="/about">About</a></li>
            <li><a href="/contact">Contact Us</a></li>
            <li><a href="/admin">Login</a></li>
            <li><a href="/logout">Logout</a></li>
            </ul>
            </div>
        </div>
        <div id='container'>
            <div id='content'>
                <% if flash[:notice] -%>
            	<p style= "color:green" class="notice"><%= flash[:notice] %></p>
	            <% end -%>
	            <%= yield %>
	</div>
	
	       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
	
            <div id='first-column'>
            	<div class="loginbox">
            		<h2 class="BoxHeaders">Login Here....</h2>
	</div>	
            	<div class="searchbox">
<h2 class="BoxHeaders">Search Catalog</h2>
	</div>
            </div>
        </div>
        <div id='footer'>
            <h6 class="footertext">&copy; Leitrim Surf Shop &trade; 2015</h6>
        </div>
</body>
</html>

app/views/site/about.html.erb
<h1>About Us</h1>
<p>Established in 1990 by the Fitzgerald Family, Surfworld is still to this day a local family business. The husband and wife team (Richie & Briohny Fitzgerald) own and run the surf shop and surf school and are lucky enough to have some pretty awesome staff working alongside them.  Not to mention their beautiful 2 year old daughter Ella who can often be found running busily around "re-arranging" everything. We use the term "re-arranging" very loosely.

The feel of a locally owned, grass roots and all core surf retailer still holds pride and place in their store. Over the last 23 years the Bundoran surfing scene has grown and Surfworld has grown with it, to become one of the most recognised names in the core Irish surfing industry. Surfworld is renowned for its excellent customer service, super fun and friendly staff, wide range of products, competitive prices, experienced local surf advice, surfboard sale quiver, fashion, wetsuits, accessories, second hand boards, surf rentals and of course surf lessons. All the staff work really hard and have loads of fun doing it. Definitely pop in next time you're in town... they're actually just a bunch of messers!</p>

app/views/site/contact.html.erb
<h2>Contact Us</h2>
<form action="http://www.SnapHost.com/captcha/send.aspx" id="ContactUsCaptchaWebForm" method="post" onsubmit="return ValidateForm(this);">
<input name="skip_WhereToSend" type="hidden" value="your@email.com" />
<input name="skip_SnapHostID" type="hidden" value="S5B7B2HGGZYY" />
<input name="skip_WhereToReturn" type="hidden" value="http://www.YourWebsiteAddress.com/ThankYouPage.htm" />
<input name="skip_Subject" type="hidden" value="Contact Us Form" />
<input name="skip_ShowUsersIp" type="hidden" value="1" />
<input name="skip_SendCopyToUser" type="hidden" value="1" />
<script type="text/javascript">
function ValidateForm(frm) {
if (frm.Name.value == "") {alert('Name is required.');frm.Name.focus();return false;}
if (frm.FromEmailAddress.value == "") {alert('Email address is required.');frm.FromEmailAddress.focus();return false;}
if (frm.FromEmailAddress.value.indexOf("@") < 1 || frm.FromEmailAddress.value.indexOf(".") < 1) {alert('Please enter a valid email address.');frm.FromEmailAddress.focus();return false;}
if (frm.Comments.value == "") {alert('Please enter comments or questions.');frm.Comments.focus();return false;}
if (frm.skip_CaptchaCode.value == "") {alert('Enter web form code.');frm.skip_CaptchaCode.focus();return false;}
return true; }
function ReloadCaptchaImage(captchaImageId) {
var obj = document.getElementById(captchaImageId);
var src = obj.src;
var date = new Date();
var pos = src.indexOf('&rad=');
if (pos >= 0) { src = src.substr(0, pos); }
obj.src = src + '&rad=' + date.getTime();
return false; }
</script>
<table border="0" cellpadding="5" cellspacing="0" width="600">
<tr>
<td><b>Name*:</b></td>
<td><input name="Name" type="text" maxlength="60" style="width:350px;" /></td>
</tr><tr>
<td><b>Phone number:</b></td>
<td><input name="PhoneNumber" type="text" maxlength="43" style="width:350px;" /></td>
</tr><tr>
<td><b>Email address*:</b></td>
<td><input name="FromEmailAddress" type="text" maxlength="60" style="width:350px;" /></td>
</tr><tr>
<td><b>Comments and questions*:</b></td>
<td><textarea name="Comments" rows="7" cols="40" style="width:350px;"></textarea></td>
</tr><tr>
<td colspan="2" align="center"> <br />
<table border="0" cellpadding="0" cellspacing="0">
<tr><td colspan="2" style="padding-bottom:18px;">
<!-- Please check our ProCaptcha service which is ad-free:
http://www.SnapHost.com/captcha/ProCaptchaOverview.aspx -->
<a href="http://www.snaphost.com/captcha/" alt="captcha validation" title="captcha validation">
captcha validation</a></td></tr>
<tr valign="top"><td> <i>Enter web form code*:</i>
<input name="skip_CaptchaCode" type="text" style="width:80px;" maxlength="6" />
</td><td>
<a href="http://www.snaphost.com/captcha/ReadyForms/ContactUsForm.aspx"><img id="CaptchaImage" alt="Contact Us form" title="HTML code for Contact Us form"
style="margin-left:20px;"
src="http://www.SnapHost.com/captcha/CaptchaImage.aspx?id=S5B7B2HGGZYY&ImgType=2" /></a><br />
<a href="#" onclick="return ReloadCaptchaImage('CaptchaImage');"><span style="font-size:12px;">reload image</span></a> </td></tr>
</table> <br />
* - required fields. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
<input name="skip_Submit" type="submit" value="Submit" />
</td></tr>
</table><br />
</form>

app/views/site/home.html.erb
<h2>Welcome to my surf shop website!</h2>



<%= image_tag("Robert.jpg", :class => "surfer")%>
 